[package]
name = "demo-graphql"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "4.0.5"
serde_json = "1.0.82"
tokio = { version = "1.20.0", features = ["full"] }
