[package]
name = "demo-webapi"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0"
tokio = { version = "1", features = ["full"] }
serde = "1"
serde_json = "1"

[lib]
name = "demo_webapi"
path = "src/lib.rs"
